---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 2.0.0
  - 2.1.6
env:
  - PUPPET_VERSION="~> 3.0"
  - PUPPET_VERSION="~> 3.0" FUTURE_PARSER="yes"
script: bundle exec rake spec
